name: Package Manager Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUSKY: 0 # Bypass husky commit hook for CI

permissions:
  contents: read

jobs:
  test-pnpm-workspace:
    name: pnpm workspace tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/pnpm

      - name: Compile packages
        run: pnpm compile

      - name: Run pnpm workspace tests
        run: pnpm ci:test -- --grep "pnpm workspace"

  test-yarn-pnp-workspace:
    name: yarn PnP workspace tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/pnpm

      - name: Compile packages
        run: pnpm compile

      - name: Run yarn PnP workspace tests
        run: pnpm ci:test -- --grep "yarn berry pnp workspace"
